### ISSUE TITLE
Feature Age

### ISSUE THREAD

**Issue by LeenDB** [GreetDB/Project_famDB#2]
#Voor het converteren zijn er 18 niet ingevuld, na het converteren zijn er ongeveer 9600 niet ingevuld.
Hoe komt dit?

**Comment by cltr** [comment]
month/months, heb het aangepast. nu opgelost?

**Comment by GreetDB** [comment]
yep, is in orde nu! terug maar 18 nans nu! de dataprocessing notebook van Leen testen, daar kan je het zien!

**Comment by GreetDB** [comment]
het lijkt alsof diegene met label '0 years' nu label nan gekregen hebben. ik wou dit eens bekeken met dit commando:
```{python}
train.loc[train.AgeuponOutcome=='0 years'][:,['AgeuponeOutcome','Age']]
```
maar dat werkt niet... wat is er fout? het eerste deel lukt maar ik slaag er niet in om dan enkel de kolommen te tonen die ik wil...

**Comment by cltr** [comment]
train.loc[...][['AgeuponOutcome','Age']]
