### ISSUE TITLE
Creatie van features

### ISSUE THREAD

**Issue by LeenDB** [GreetDB/Project_famDB#5]
Nu worden de features toegevoegd aan het dataframe en dan achteraf worden de originele verwijderd.
Of denken jullie dat het beter is om direct een nieuw dataframe aan te maken?

**Comment by cltr** [comment]
Misschien gewoon nieuwe maken, dan is verwijderen niet meer nodig.

**Comment by LeenDB** [comment]
Ok, dit breng ik nu in orde.

**Comment by LeenDB** [comment]
Done.
Als er nu een feature aangemaakt wordt is dit nu gewoon een dataframe.
En deze worden dan allemaal samengevoegd tot 1 dataframe (zoals op regel 16 van input_data).

Er was wel een vergetelheid bij het converteren van de categorische waarden. Eerst werd dit enkel gedaan voor de trainingsdata, maar natuurlijk ook de test data moet omgezet worden.
