### ISSUE TITLE
rows met NaN

### ISSUE THREAD

**Issue by GreetDB** [GreetDB/Project_famDB#6]
wat doen we met de rijen die een nan hebben na creatie van de features en convertie? verwijderen we die?

**Comment by cltr** [comment]
Als de afwezigheid random is (denk ik wel), kunnen we ze veilig verwijderen, als we niet te veel observaties verliezen natuurlijk. Kunnen ook overgaan tot imputatie indien noodzakelijk.

**Comment by LeenDB** [comment]
Had je niet gezegd in jouw eerste code dat als je ze weg laat je, je heel weinig data overlaat?

**Comment by GreetDB** [comment]
is bij Age dat we nog een paar nan's hebben (18). bij de andere features is de nan /unknown vervangen door een integer door de  labelencoder functie. dat hebben we niet gedaan met age, dus zal nu eventueel de nan's vervangen door 0 want als ik ze verwijder mapt men train_labels niet meer :-)

**Comment by LeenDB** [comment]
Nog een kleine opmerking: zou het niet beter zijn om daar -1 in te vullen aangezien nul ook al voorkomt in de echt dataset en anders zet je niet gekend gelijk aan net geboren.

**Comment by GreetDB** [comment]
owke, slim! ik heb het veranderd!
